---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-certificates
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      hosts:
        - "ca.molier.net"
        - "ca.home.molier.net"
        - "ca.core.k8s.local"
