---
apiVersion: v1
kind: Secret
type: smallstep.com/ca-password
metadata:
    name: step-certificates-step-certificates-ca-password
    namespace: step-certificates
stringData:
    password: ENC[AES256_GCM,data:9NXfPzo6qQH1fuAomuiJYamKVfbZKPRyIRE+XiKyiu4=,iv:peKJ8rrxtsJ19W87zH6iH0wWnO29pyiLGZHmtKimY9I=,tag:W80LYInSGwD3/M3M8NQKrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmnk6eyeyxv4uvvlf35kra3fugznljt5fe0wrr0aje8c4g9p5p8smju584
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZG5SaFBoUU9MczhTT25B
            Mkg0bVJOYVlMRzFnd3lxaENQYkphNUxvbUhvCktTOC9IUm9zMU40azNpSkdLM3J4
            UXgraFBRcDdQd3dET3RaalN3cm0xQlUKLS0tIEgvN21SYi9ia0FzcmZ6TkVwMHpy
            VXcxV1RFZ1NrN3BWWWJmRU1FVHRXN1UKqpCHcmQMVftab8q0y7AI+84rN9560U0Q
            XuJd/Kl5jCuTIwUfzZNGHZ9CX2SyTq5SXvi1e0zOpNVTEYEDGr/Kyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j3c9j0d423g2cwvev5crrq8z853ldgznndrxltlzsh2r9dzr3ctswem2hj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcG9waFZhSU5WM0RvaFds
            NHhZMWxoaXY4VTIvMlJtTnUrVmcvS0lXSndVCnFRcFd0dUJoMkJBenJ5eitpcGpp
            bk50ZWowcmhLQnJoUlJUc1YvblcrOTAKLS0tIGJqdGZvcE8xSEtrdEhYNXRWdFN5
            dXhQalV6VXpYbUxKMTBtalI1M3lHdzQKtHhskFpp54QHPnikcywEkkLNhfGl1i6y
            WEjo7Uw++OvzFyLecU/Vkb/+BUUNblI3/Jt+gHEaDs0thhoccaEsxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-11T22:53:36Z"
    mac: ENC[AES256_GCM,data:HyMgwaAOOkCxjt25e6wd9q4N0dcIOdq9OIP7qS+PcTJY0qDApuiG2vX9E3ZtE9+m/Nb0nIUg1N5sf6hEWOhULUOZojmoBpi/ZGI2M/P1aLI1SQUqplLIrZ29HrjW99gjYdCTuSPY3Rid2DlsqcqzETOhgvDowYBfWzg7ZY8vZrE=,iv:+E7aFrF5ZUfPwbmS97zSOWURHQosDmq8B+GHw8B3ul0=,tag:61kXUJLFLO1xaDlIsSPIBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
