apiVersion: v1
kind: ConfigMap
metadata:
  name: public-certs
data:
  step_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIBpzCCAU6gAwIBAgIRAJuby7mYUqTVMy0DlfrSBZEwCgYIKoZIzj0EAwIwMjET
    MBEGA1UEChMKTW9saWVyLk5FVDEbMBkGA1UEAxMSTW9saWVyLk5FVCBSb290IENB
    MB4XDTIzMDMxMTIxNTk0M1oXDTMzMDMwODIxNTk0M1owMjETMBEGA1UEChMKTW9s
    aWVyLk5FVDEbMBkGA1UEAxMSTW9saWVyLk5FVCBSb290IENBMFkwEwYHKoZIzj0C
    AQYIKoZIzj0DAQcDQgAEDuVLImS63SmvDjqZ2WeoexUHusCBIMBpX3nETpalQ4wW
    9L/K8Lj35nBPbnqsiqOYqLdCe0JVf6Y+ac1Zct93b6NFMEMwDgYDVR0PAQH/BAQD
    AgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFJqXi3axc2zuqtOOEQPs
    GPtkE4QnMAoGCCqGSM49BAMCA0cAMEQCIDGltdBdwbxjq/2n3vh/NT6SO1reHumw
    ZOyPRVdG+lAKAiBVbz1rxvxjZ6o/S+4Y+jNZjKibe81F3x1kcXQWXPN5kA==
    -----END CERTIFICATE-----
