---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  values:
    volumes:
      - name: traefik-public-certs
        mounthPath: "/certs"
        type: configMap
    additionalArguments:
      - "--serversTransport.rootCAs=/certs/step_ca.crt"
