apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth
    namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Js48Oxc=,iv:d2UGXPmD7kZ+hC99z3cxmzJw8cQDXwweDyc4JXArY0I=,tag:WiF1G/N+Mol7iSW9TWRRSg==,type:str]
    password: ENC[AES256_GCM,data:4+hr1FchoTq9oYw=,iv:3AoAAhEU8NDsVbItHe3/5BDCok5l80ebaED+TZQHBPA=,tag:8QJnBRPc9HlprEKX5U45Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmnk6eyeyxv4uvvlf35kra3fugznljt5fe0wrr0aje8c4g9p5p8smju584
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ODlTVmJINGNvTmFMRXlv
            QURiWHNaWG1XZlRlcWE1WDQ0amd1Z21uYnlzCldaNnBhb2FJY2RqeFpQbGtvMVd3
            QmU4ci92czZiZTRYeGplb2tjWFNrWnMKLS0tIFFBckorQnluRnVNb2FvcVh2bnMr
            cHp3Q1E5Um4yc0RIbngwSUNQa3RrMzQKbHLudXlzDBjG+kJNmEd8r/IGR2xGy2q3
            3iM5QzsX/fgZZJwQVwLGXsmrL19l0j/RD8O/+i0X7hqEkXo+oe39qA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j3c9j0d423g2cwvev5crrq8z853ldgznndrxltlzsh2r9dzr3ctswem2hj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRFlJbkZEcUQzc09oR3Ri
            WkwvVnV1a0ZhYm9KNmpFWXF3R2xNc0QwU1VJCnZDbG5kYjgyNFpGVUNhYkJKSGNj
            RTQ0SEpXTlpnVkFyYlFKdkI3ZW9ncFUKLS0tIDBLei94KzJGYm03eDdEeVhmamhH
            bEwvdWREeml6K0hZRTN0dDBPTmQvRjAKEtm63CrX4HXv/RS++2UBpBInkGmrRHrj
            kTBwV5WfsMm3L4G7wB4EIuy8757HHoNwUVktdvHn9bo8VRn4fHB61w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T12:42:47Z"
    mac: ENC[AES256_GCM,data:cJ3lN+R2HYijnJjihjc1A8wadzzy2/qe2be5Om8LC2zCrUR+vclTSg76F2lcZvN3qPgWSj2G7/SgPYmkx4FPQen5O2WZ9D0dMXUig08Jlp2cLYkYbDoKrl34i/CH0uNUK/afytUNoRgbp3a90PeFUB9hgoVBTUyVwp/cztq76zU=,iv:s7gSHe7/tNJomabdIOpKiNpMo9Yk/0m9yf/FhnSHG78=,tag:yzOqBUbninmg+gVOxB4kkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
