---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: step-certificates
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  interval: 5m0s
  path: ./kubernetes/apps/base/step-certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
