---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  dependsOn:
    - name: infrastructure
  interval: 15m0s
  path: ./kubernetes/apps/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
