---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  interval: 15m0s
  path: ./kubernetes/infrastructure/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
