---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  dependsOn:
    - name: kube-prometheus-stack
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: flux-system
  interval: 5m0s
  path: ./kubernetes/infrastructure/base/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
