---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring-config
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  interval: 5m0s
  path: ./kubernetes/infrastructure/base/monitoring/flux-monitoring-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
