apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-server
  namespace: networking
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: dhcp-server
      app.kubernetes.io/part-of: networking
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhcp-server
        app.kubernetes.io/instance: dhcp-server
        app.kubernetes.io/component: dhcp-server
        app.kubernetes.io/part-of: networking
    spec:
      hostNetwork: true
      containers:
        - name: dhcp-server
          image: ghcr.io/remkio/dhcp-server:latest
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 200Mi
              cpu: 500m
          volumeMounts:
            - mountPath: "/var/lib/dhcp"
              name: dhcp-leases
              readOnly: false
            - mountPath: "/etc/dhcp/"
              name: dhcp-config
              readOnly: true
            - mountPath: "/etc/dhcp/secrets"
              name: dhcp-secrets
              readOnly: true
          ports:
            - containerPort: 67
              hostPort: 67
              protocol: UDP
              name: dhcp
      volumes:
        - name: dhcp-leases
          persistentVolumeClaim:
            claimName: dhcp-leases
        - name: dhcp-config
          configMap:
            name: dhcp-config
        - name: dhcp-secrets
          configMap:
            name: ddns-secrets
