---
name: Containers DHCP Server CI

on:
  push:
    paths: ["containers/dhcp-server/**"]
  pull_request:
    branches: ["main"]
    paths: ["containers/dhcp-server/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: 'containers/dhcp-server'
          platforms: linux/amd64, linux/arm64
          push: ${{ github.ref_name == 'main' && \
                    github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/remkio/dhcp-server:4.4.3_p1-r1
            ghcr.io/remkio/dhcp-server:4.4
            ghcr.io/remkio/dhcp-server:4
            ghcr.io/remkio/dhcp-server:latest
